# Generated by Django 4.0.4 on 2022-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
